#!/bin/bash
#/ Usage: script/setup

set -e

log() { echo "==> $*"; }
abort() { echo "!!! $*" >&2; exit 1; }

create_symbolic_link_of_dotfiles() {
  for dotfile in .?*; do
    case "$dotfile" in
      ".." ) continue ;;
      ".DS_Store" ) continue ;;
      "*.elc" ) continue ;;
      ".git" | ".gitignore" | ".gitmodules" | ".module" ) continue ;;
      * )
        if [ -f "$HOME/$dotfile" ] || [ -d "$HOME/$dotfile" ]; then
          if [ ! -L "$HOME/$dotfile" ]; then
            # シンボリックリンクではないファイルが存在する
            echo "${dotfile} is already exists."
            echo "------ $HOME/${dotfile} ------"
            cat $HOME/${dotfile}
            echo "------"
            echo "Remove existing $HOME/${dotfile} and create new one."
          fi

          rm $HOME/${dotfile}
        fi

        ln -is $HOME/.dotfiles/${dotfile} $HOME
        echo "~/${dotfile} -> $HOME/.dotfiles/${dotfile}"
        ;;
    esac
  done
}

log "Create symbolic link of dotfiles:"
create_symbolic_link_of_dotfiles
