#!/bin/sh

if [ -f "/Library/Developer/CommandLineTools/usr/bin/git" ]; then
    echo "git is already exists :)"
else
    echo "git is not exists :("
    exit 1
fi

SCRIPT_DIR=$(cd $(dirname $BASH_SOURCE); pwd)

if [ $( uname ) == "Darwin" ]; then
  sh $SCRIPT_DIR/create_symbolick_links.sh
  sh $SCRIPT_DIR/install_zsh_settings.sh
  sh $SCRIPT_DIR/install_bash_settings.sh
  sh $SCRIPT_DIR/install_anyenv.sh
  sh $SCRIPT_DIR/install_fonts.sh
else
  echo "Nothing to do..."
fi
